name: mix
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^1.3.0
  flutter_riverpod: ^2.3.6
  flutter_robusta: ^0.2.0
  flutter_robusta_auth: ^0.1.0+1
  # flutter_robusta:
  #   path: ../../FastBoy_Project/robusta/packages/flutter_robusta
  # flutter_robusta_auth:
  #   path: ../../FastBoy_Project/robusta/packages/flutter_robusta_auth
  go_router_plus: ^4.1.1
  equatable: ^2.0.5
  google_fonts: ^4.0.4
  fl_chart: ^0.62.0
  intl: ^0.18.1
  scrollable_positioned_list: ^0.3.8
  robusta_runner: ^0.2.0+1
  # robusta_runner:
  #   path: ../../FastBoy_Project/robusta/packages/robusta_runner
  # robusta_firebase_core:
  #   path: ../../FastBoy_Project/robusta/packages/robusta_firebase_core
  firebase_database: ^10.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
